rm apparentment_data/aargau/results.json
rm apparentment_data/appenzell-ausserrhoden/results.json
rm apparentment_data/appenzell-innerrhoden/results.json
rm apparentment_data/basel-landschaft/results.json
rm apparentment_data/basel-stadt/results.json
rm apparentment_data/bern/results.json
rm apparentment_data/freiburg/results.json
rm apparentment_data/genf/results.json
rm apparentment_data/glarus/results.json
rm apparentment_data/graubunden/results.json
rm apparentment_data/jura/results.json
rm apparentment_data/luzern/results.json
rm apparentment_data/nauenburg/results.json
rm apparentment_data/nidwalden/results.json
rm apparentment_data/obwalden/results.json
rm apparentment_data/schaffhausen/results.json
rm apparentment_data/schwyz/results.json
rm apparentment_data/solothurn/results.json
rm apparentment_data/st-gallen/results.json
rm apparentment_data/tessin/results.json
rm apparentment_data/thurgau/results.json
rm apparentment_data/uri/results.json
rm apparentment_data/waadt/results.json
rm apparentment_data/wallis/results.json
rm apparentment_data/zug/results.json
rm apparentment_data/zurich/results.json